import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Lint rules that catch what the compiler cannot.
 *
 * Architectural import boundaries (§ ADR-0003) are NOT enforced here — they are
 * enforced by `scripts/boundary-check.ts`, which understands package ownership
 * and needs no plugin to do it.
 */
export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/.next/**",
      "**/.next-e2e/**",
      "**/storybook-static/**",
      // Generated by `next build` on every run, and not ours to style.
      "apps/web/next-env.d.ts",
      "packages/db/migrations/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "separate-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  {
    // Scripts and seeds are operator tools; printing to stdout is their job.
    files: ["scripts/**/*.ts", "packages/db/src/seeds/**/*.ts"],
    rules: { "no-console": "off" },
  },
  {
    /*
     * The browser half. `globals.browser` rather than `globals.node`, so a
     * component reaching for `process` or `__dirname` is a lint error here rather
     * than a blank screen in production.
     */
    files: ["apps/web/**/*.ts", "apps/web/**/*.tsx"],
    languageOptions: {
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  },
  {
    // Config and tooling inside the web app run in Node, not the browser.
    files: [
      "apps/web/*.ts",
      "apps/web/.storybook/**/*.ts",
      "apps/web/e2e/**/*.ts",
      "apps/web/src/ui/catalog-coverage.test.ts",
      "apps/web/src/testing/**/*.ts",
    ],
    languageOptions: { globals: { ...globals.node } },
  },
);
