import type { WorkspaceBackupV19 } from "@vuarau/domain-contracts";

export function backupActorIds(payload: WorkspaceBackupV19["payload"]): string[] {
  return [
    ...payload.cashAccounts.map((row) => row["custodianActorId"]),
    ...payload.expenses.map((row) => row["actorId"]),
    ...payload.expenseReversals.map((row) => row["actorId"]),
    ...payload.cashTransfers.map((row) => row["actorId"]),
    ...payload.cashTransferReversals.map((row) => row["actorId"]),
    ...payload.cashAdjustments.map((row) => row["actorId"]),
    ...payload.cashMovements.map((row) => row["actorId"]),
    ...payload.accountEntries.map((row) => row["actorId"]),
    ...payload.audit.map((row) => row["actorId"]),
    ...payload.supplierAccountEntries.map((row) => row["actorId"]),
    ...payload.receipts.map((row) => row["actorId"]),
    ...payload.receiptReversals.map((row) => row["actorId"]),
    ...payload.inventoryMovements.map((row) => row["actorId"]),
    ...payload.stocktakeSessions.map((row) => row["actorId"]),
    ...payload.stocktakeCounts.map((row) => row["actorId"]),
    ...payload.goodsArrivals.map((row) => row["actorId"]),
    ...payload.goodsArrivalReversals.map((row) => row["actorId"]),
    ...payload.qualityInspections.map((row) => row["actorId"]),
    ...payload.qualityInspectionReversals.map((row) => row["actorId"]),
    ...payload.qualityDispositions.map((row) => row["actorId"]),
    ...payload.qualityDispositionReversals.map((row) => row["actorId"]),
    ...payload.deliveries.map((row) => row["actorId"]),
    ...payload.deliveryReturns.map((row) => row["actorId"]),
    ...payload.documents.map((row) => row["generatedBy"]),
    ...payload.documentShares.flatMap((row) => [row["createdBy"], row["revokedBy"]]),
    ...payload.priceRules.map((row) => row["actorId"]),
    ...payload.costObservations.map((row) => row["actorId"]),
    ...payload.reconciliationObservations.map((row) => row["actorId"]),
    ...payload.debtObservations.map((row) => row["actorId"]),
    ...payload.paymentAllocations.map((row) => row["actorId"]),
    ...payload.paymentAllocationReversals.map((row) => row["actorId"]),
    ...payload.supplyCommitmentObservations.map((row) => row["actorId"]),
    ...payload.supplierObservations.map((row) => row["actorId"]),
    ...payload.demandObservations.map((row) => row["actorId"]),
    ...payload.workspacePolicies.flatMap((row) => [
      row["createdBy"],
      row["approvedBy"],
      row["retiredBy"],
    ]),
  ].filter((value): value is string => typeof value === "string");
}
