/**
 * Every user-visible state named in `docs/06-api-contracts/ui-state-catalog.md`.
 *
 * The Markdown document is the source of truth. TC-WEB-012 compares it with this
 * list and Storybook `coversState(...)` declarations so coverage cannot silently
 * shrink to an obsolete bounded context.
 */
export const UI_STATE_CATALOG = [
  "signed_out",
  "no_workspace_membership",
  "loading",
  "empty",
  "validation_error",
  "business_rejection",
  "permission_denied",
  "stale_version",
  "duplicate_safe_retry",
  "command_in_progress",
  "unknown_network_outcome",
  "balance_receivable",
  "balance_settled",
  "balance_customer_credit",
  "sale_draft",
  "sale_discarded",
  "sale_posted",
  "sale_voided",
  "sale_replaced",
  "customer_active",
  "customer_inactive",
  "membership_revoked",
  "last_owner_protected",
  "no_due_date",
  "due",
  "overdue",
  "payment_recorded",
  "payment_partially_reversed",
  "payment_reversed",
  "reversal_amount_exceeded",
  "supplier_active",
  "supplier_inactive",
  "supplier_balance_payable",
  "supplier_balance_settled",
  "supplier_balance_credit",
  "purchase_draft",
  "purchase_confirmed",
  "purchase_discarded",
  "purchase_voided",
  "product_active",
  "product_inactive",
  "quality_grade_active",
  "quality_grade_inactive",
  "no_active_quality_grades",
  "receipt_active",
  "receipt_reversed",
  "inventory_positive",
  "inventory_zero",
  "inventory_negative",
  "inventory_legacy_unclassified",
  "inventory_reclassification",
  "inventory_spoilage",
  "delivery_draft",
  "delivery_cancelled",
  "delivery_dispatched",
  "delivery_delivered",
  "fulfilment_unfulfilled",
  "fulfilment_partially_fulfilled",
  "fulfilment_fulfilled",
  "fulfilment_returned_partial",
  "fulfilment_attention",
  "document_share_available",
  "document_share_expired",
  "document_share_revoked",
  "reconciliation_consistent",
  "reconciliation_inconsistent",
  "reconciliation_not_found",
  "reconciliation_integrity_failure",
  "workspace_integrity_healthy",
  "workspace_integrity_attention",
] as const;

export type UiCatalogState = (typeof UI_STATE_CATALOG)[number];

export function coversState(state: UiCatalogState): { catalogState: UiCatalogState } {
  return { catalogState: state };
}
