-- Order → Sale, and the debt ledger → the customer account ledger.
--
-- Written by hand rather than generated, because drizzle-kit cannot tell a rename
-- from a drop-and-create and would have emitted DROP TABLE for every money table
-- in the system. Every statement below is a RENAME or an ADD: **no data is
-- dropped, moved, or rewritten**, and the migration is reversible by inverting it.
-- The accompanying snapshot was generated by drizzle-kit from the new schema, so
-- the next `pnpm db:generate` produces a clean diff.
--
-- Decisions: ADR-0012 (void and replacement), ADR-0013 (sale, not order).
-- Rules: BR-SALE-008, BR-SALE-012, BR-SALE-013, BR-SALE-017, BR-ACCOUNT-009.
--
-- Two enum values disappear and are worth naming:
--
--   order_status 'confirmed' → sale_status 'posted'      (renamed value, data kept)
--   order_status 'cancelled' → gone                       (see below)
--
-- `cancelled` was never reachable: no CancelOrder command was ever implemented,
-- so no row can carry it. The CASE below still handles it explicitly and fails
-- loudly rather than silently mapping it to something plausible — if a row did
-- exist, a human needs to decide whether it was a discarded draft or a voided
-- sale, and those have different money.

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------
ALTER TABLE "orders" RENAME TO "sales";--> statement-breakpoint
ALTER TABLE "order_lines" RENAME TO "sale_lines";--> statement-breakpoint
ALTER TABLE "debt_ledger_entries" RENAME TO "customer_account_entries";--> statement-breakpoint
ALTER TABLE "customer_debt_summaries" RENAME TO "customer_account_balances";--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. Columns
-- ---------------------------------------------------------------------------
ALTER TABLE "sale_lines" RENAME COLUMN "order_id" TO "sale_id";--> statement-breakpoint
ALTER TABLE "sales" RENAME COLUMN "confirmed_at" TO "posted_at";--> statement-breakpoint

-- `cancelled_at` goes with the concept. A posted sale is now voided — recorded in
-- its own table with a reason and an actor — and a draft is discarded. A single
-- nullable timestamp could express neither well (ADR-0012).
ALTER TABLE "sales" DROP COLUMN "cancelled_at";--> statement-breakpoint

-- Nullable, and a null is never overdue (BR-SALE-017). Most depot sales are null.
ALTER TABLE "sales" ADD COLUMN "due_at" timestamp with time zone;--> statement-breakpoint

-- Set once at draft creation; never rewritten, because the sale it points at is
-- immutable (BR-SALE-016).
ALTER TABLE "sales" ADD COLUMN "replaces_sale_id" uuid;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. Constraints and indexes carried over from the old names
-- ---------------------------------------------------------------------------
ALTER TABLE "sales" RENAME CONSTRAINT "orders_workspace_id_workspaces_id_fk" TO "sales_workspace_id_workspaces_id_fk";--> statement-breakpoint
ALTER TABLE "sales" RENAME CONSTRAINT "orders_customer_id_customers_id_fk" TO "sales_customer_id_customers_id_fk";--> statement-breakpoint
ALTER TABLE "sale_lines" RENAME CONSTRAINT "order_lines_workspace_id_workspaces_id_fk" TO "sale_lines_workspace_id_workspaces_id_fk";--> statement-breakpoint
ALTER TABLE "sale_lines" RENAME CONSTRAINT "order_lines_order_id_orders_id_fk" TO "sale_lines_sale_id_sales_id_fk";--> statement-breakpoint
ALTER TABLE "sale_lines" RENAME CONSTRAINT "order_lines_product_id_products_id_fk" TO "sale_lines_product_id_products_id_fk";--> statement-breakpoint
ALTER TABLE "customer_account_entries" RENAME CONSTRAINT "debt_ledger_entries_workspace_id_workspaces_id_fk" TO "customer_account_entries_workspace_id_workspaces_id_fk";--> statement-breakpoint
ALTER TABLE "customer_account_entries" RENAME CONSTRAINT "debt_ledger_entries_customer_id_customers_id_fk" TO "customer_account_entries_customer_id_customers_id_fk";--> statement-breakpoint
ALTER TABLE "customer_account_entries" RENAME CONSTRAINT "debt_ledger_entries_actor_id_actors_id_fk" TO "customer_account_entries_actor_id_actors_id_fk";--> statement-breakpoint
ALTER TABLE "customer_account_entries" RENAME CONSTRAINT "debt_ledger_entries_source_unique" TO "customer_account_entries_source_unique";--> statement-breakpoint
ALTER TABLE "customer_account_balances" RENAME CONSTRAINT "customer_debt_summaries_workspace_id_workspaces_id_fk" TO "customer_account_balances_workspace_id_workspaces_id_fk";--> statement-breakpoint
ALTER TABLE "customer_account_balances" RENAME CONSTRAINT "customer_debt_summaries_customer_id_customers_id_fk" TO "customer_account_balances_customer_id_customers_id_fk";--> statement-breakpoint

ALTER INDEX "orders_workspace_status_time_idx" RENAME TO "sales_workspace_status_time_idx";--> statement-breakpoint
ALTER INDEX "orders_workspace_customer_time_idx" RENAME TO "sales_workspace_customer_time_idx";--> statement-breakpoint
ALTER INDEX "order_lines_order_idx" RENAME TO "sale_lines_sale_idx";--> statement-breakpoint
ALTER INDEX "debt_ledger_entries_workspace_customer_time_idx" RENAME TO "customer_account_entries_workspace_customer_time_idx";--> statement-breakpoint
ALTER INDEX "debt_ledger_entries_command_idx" RENAME TO "customer_account_entries_command_idx";--> statement-breakpoint

CREATE INDEX "sales_replaces_idx" ON "sales" USING btree ("replaces_sale_id");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 4. Enums
-- ---------------------------------------------------------------------------
-- A rename preserves every stored value; only the label changes.
ALTER TYPE "public"."ledger_source_type" RENAME TO "account_entry_source_type";--> statement-breakpoint
ALTER TYPE "public"."account_entry_source_type" RENAME VALUE 'order_confirmation' TO 'sale_posting';--> statement-breakpoint
ALTER TYPE "public"."account_entry_source_type" ADD VALUE 'sale_void' AFTER 'sale_posting';--> statement-breakpoint

ALTER TYPE "public"."debt_adjustment_reason_code" ADD VALUE 'dispute_settlement' AFTER 'write_off';--> statement-breakpoint
ALTER TYPE "public"."debt_adjustment_reason_code" ADD VALUE 'migration_correction' AFTER 'dispute_settlement';--> statement-breakpoint

ALTER TYPE "public"."audit_aggregate_type" RENAME VALUE 'order' TO 'sale';--> statement-breakpoint
ALTER TYPE "public"."audit_action" RENAME VALUE 'order.created' TO 'sale.draft_created';--> statement-breakpoint
ALTER TYPE "public"."audit_action" RENAME VALUE 'order.confirmed' TO 'sale.posted';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'sale.voided' AFTER 'sale.posted';--> statement-breakpoint

CREATE TYPE "public"."sale_void_reason_code" AS ENUM('wrong_amount', 'wrong_customer', 'goods_returned', 'duplicate_entry', 'cancelled_by_customer', 'other');--> statement-breakpoint

-- `order_status` loses a value, and Postgres cannot drop one, so the type is
-- rebuilt. `USING` maps 'confirmed' to 'posted' and refuses anything else.
CREATE TYPE "public"."sale_status" AS ENUM('draft', 'posted');--> statement-breakpoint
ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sale_status"
  USING (CASE "status"::text
           WHEN 'draft' THEN 'draft'
           WHEN 'confirmed' THEN 'posted'
         END)::"public"."sale_status";--> statement-breakpoint
DROP TYPE "public"."order_status";--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 5. The void table (ADR-0012)
-- ---------------------------------------------------------------------------
-- `UNIQUE (sale_id)` is the structural half of BR-SALE-013: two concurrent voids
-- cannot both land, so a customer cannot be credited twice for one mistake even
-- if the row lock and the domain check were both bypassed.
CREATE TABLE "sale_voids" (
	"id" uuid PRIMARY KEY NOT NULL,
	"workspace_id" uuid NOT NULL,
	"sale_id" uuid NOT NULL,
	"reason_code" "sale_void_reason_code" NOT NULL,
	"reason" text NOT NULL,
	"amount_minor" bigint NOT NULL,
	"currency" "currency_code" NOT NULL,
	"transaction_time" timestamp with time zone NOT NULL,
	"recorded_at" timestamp with time zone NOT NULL,
	"actor_id" uuid NOT NULL,
	"command_id" uuid NOT NULL,
	CONSTRAINT "sale_voids_sale_unique" UNIQUE("sale_id")
);--> statement-breakpoint
ALTER TABLE "sale_voids" ADD CONSTRAINT "sale_voids_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_voids" ADD CONSTRAINT "sale_voids_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "public"."sales"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_voids" ADD CONSTRAINT "sale_voids_actor_id_actors_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."actors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sale_voids_workspace_time_idx" ON "sale_voids" USING btree ("workspace_id","transaction_time");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 6. Rejection codes
-- ---------------------------------------------------------------------------
-- Six ORDER_* codes retire and four SALE_* codes appear; ORDER_CANCELLED goes
-- entirely. Postgres cannot drop enum values, so the type is rebuilt. See the
-- error code catalog for why renaming codes — normally forbidden — is a
-- deliberate one-time exception with no clients in the field.
ALTER TYPE "public"."domain_rejection_code" RENAME TO "domain_rejection_code_old";--> statement-breakpoint
CREATE TYPE "public"."domain_rejection_code" AS ENUM('AUTHENTICATION_REQUIRED', 'AUTHENTICATION_INVALID', 'ACTOR_NOT_FOUND', 'ACTOR_IMPERSONATION_DENIED', 'WORKSPACE_ACCESS_DENIED', 'WORKSPACE_MEMBERSHIP_INACTIVE', 'PERMISSION_DENIED', 'CUSTOMER_NOT_FOUND', 'CUSTOMER_NAME_REQUIRED', 'SALE_NOT_FOUND', 'SALE_EMPTY', 'SALE_LINE_INVALID', 'SALE_ALREADY_POSTED', 'SALE_VERSION_CONFLICT', 'SALE_CURRENCY_MISMATCH', 'SALE_IMMUTABLE', 'SALE_NOT_POSTED', 'SALE_ALREADY_VOIDED', 'SALE_VOID_REASON_REQUIRED', 'PAYMENT_AMOUNT_INVALID', 'PAYMENT_NOT_FOUND', 'PAYMENT_ALREADY_REVERSED', 'PAYMENT_REVERSAL_EXCEEDS_REMAINING_AMOUNT', 'PAYMENT_REVERSAL_REASON_REQUIRED', 'PAYMENT_VERSION_CONFLICT', 'PAYMENT_CURRENCY_MISMATCH', 'DEBT_ADJUSTMENT_REASON_REQUIRED', 'DEBT_ADJUSTMENT_AMOUNT_INVALID', 'DUPLICATE_COMMAND', 'IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD', 'COMMAND_IN_PROGRESS', 'INVALID_COMMAND_PAYLOAD', 'TRANSACTION_TIME_IN_FUTURE', 'COMMAND_NOT_AVAILABLE');--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "rejection_code" TYPE "public"."domain_rejection_code"
  USING (CASE "rejection_code"::text
           WHEN 'ORDER_NOT_FOUND' THEN 'SALE_NOT_FOUND'
           WHEN 'ORDER_EMPTY' THEN 'SALE_EMPTY'
           WHEN 'ORDER_LINE_INVALID' THEN 'SALE_LINE_INVALID'
           WHEN 'ORDER_ALREADY_CONFIRMED' THEN 'SALE_ALREADY_POSTED'
           WHEN 'ORDER_VERSION_CONFLICT' THEN 'SALE_VERSION_CONFLICT'
           WHEN 'ORDER_CURRENCY_MISMATCH' THEN 'SALE_CURRENCY_MISMATCH'
           ELSE "rejection_code"::text
         END)::"public"."domain_rejection_code";--> statement-breakpoint
DROP TYPE "public"."domain_rejection_code_old";--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 7. Guards
-- ---------------------------------------------------------------------------
-- The trigger functions keep working across the table renames — a trigger follows
-- its table — but the project is now vuarau-ops, and migration 0001 is immutable,
-- so the functions are renamed here.
ALTER FUNCTION vuanha_forbid_mutation() RENAME TO vuarau_forbid_mutation;--> statement-breakpoint
ALTER FUNCTION vuanha_forbid_delete() RENAME TO vuarau_forbid_delete;--> statement-breakpoint
ALTER TRIGGER debt_ledger_entries_append_only ON customer_account_entries RENAME TO customer_account_entries_append_only;--> statement-breakpoint
ALTER TRIGGER orders_no_delete ON sales RENAME TO sales_no_delete;--> statement-breakpoint
ALTER TRIGGER order_lines_no_delete ON sale_lines RENAME TO sale_lines_no_delete;--> statement-breakpoint

-- A void record is a financial fact. Nothing may edit or remove one.
CREATE TRIGGER sale_voids_append_only
  BEFORE UPDATE OR DELETE ON sale_voids
  FOR EACH ROW EXECUTE FUNCTION vuarau_forbid_mutation();--> statement-breakpoint

-- BR-SALE-008, strengthened. Until now `sales` and `sale_lines` carried a
-- delete-only guard, because a draft legitimately changes. A *posted* sale must
-- not: it is a historical claim about what a customer took and at what price, and
-- editing it after the fact is the failure this system exists to prevent.
--
-- Voiding does not trip this. A void writes to `sale_voids` and appends a
-- compensating account entry; it does not touch the sale.
CREATE OR REPLACE FUNCTION vuarau_forbid_posted_sale_change() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION
    '% on a posted sale is forbidden: a posted sale is immutable. Void it and post a replacement instead.',
    TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint

CREATE TRIGGER sales_posted_immutable
  BEFORE UPDATE ON sales
  FOR EACH ROW WHEN (OLD.status = 'posted')
  EXECUTE FUNCTION vuarau_forbid_posted_sale_change();--> statement-breakpoint

CREATE TRIGGER sale_lines_posted_immutable
  BEFORE UPDATE ON sale_lines
  FOR EACH ROW EXECUTE FUNCTION vuarau_forbid_posted_sale_change();
