import { z } from "zod";

/**
 * The stable vocabulary of business refusals.
 *
 * These strings are API. They may be deprecated but never renamed or reused, and
 * no client may branch on `message` — messages will become Vietnamese and will
 * change. See docs/04-business-rules/error-code-catalog.md.
 */
export const DOMAIN_REJECTION_CODES = [
  // --- authentication -------------------------------------------------------
  /** No credential was presented at all. */
  "AUTHENTICATION_REQUIRED",
  /** A credential was presented and is not trustworthy: bad signature, expired,
   *  wrong issuer or audience. Deliberately does not say which. */
  "AUTHENTICATION_INVALID",
  /** The token verified, but its subject maps to no actor in this system. */
  "ACTOR_NOT_FOUND",
  /** The command claims an `actorId` that is not the authenticated actor. */
  "ACTOR_IMPERSONATION_DENIED",

  // --- workspace / authorization -------------------------------------------
  /** The actor is not a member of the target workspace. */
  "WORKSPACE_ACCESS_DENIED",
  /** Membership exists but has been deactivated. Distinct from never having had
   *  access, because the operator's remedy is different. */
  "WORKSPACE_MEMBERSHIP_INACTIVE",
  /** The actor is an active member, but their role lacks the permission. */
  "PERMISSION_DENIED",
  /**
   * Revoking the only remaining active owner. Refused, because a depot that locks
   * itself out of its own account book has no self-service remedy (BR-AUTH-007).
   */
  "WORKSPACE_LAST_OWNER",
  "WORKSPACE_MEMBER_NOT_FOUND",
  "WORKSPACE_MEMBER_ALREADY_EXISTS",
  "WORKSPACE_MEMBER_ALREADY_ACTIVE",
  "WORKSPACE_MEMBER_ROLE_UNCHANGED",
  "WORKSPACE_MEMBER_ROLE_CONFLICT",
  "WORKSPACE_MEMBER_SELF_ROLE_CHANGE_DENIED",
  "WORKSPACE_PROFILE_VERSION_CONFLICT",
  "WORKSPACE_PROFILE_UNCHANGED",
  "WORKSPACE_POLICY_DEFINITION_INVALID",
  "WORKSPACE_WORKFLOW_DISABLED",
  "BACKUP_DIGEST_INVALID",
  "BACKUP_UNSAFE_TARGET",
  "BACKUP_INTEGRITY_ERROR",

  // --- customer -------------------------------------------------------------
  "CUSTOMER_NOT_FOUND",
  "CUSTOMER_NAME_REQUIRED",
  "CUSTOMER_VERSION_CONFLICT",
  /** Deactivating a customer who already is. Their balance is untouched either way. */
  "CUSTOMER_ALREADY_INACTIVE",
  "CUSTOMER_ALREADY_ACTIVE",

  // --- product --------------------------------------------------------------
  "PRODUCT_NOT_FOUND",
  "PRODUCT_VERSION_CONFLICT",
  "QUALITY_GRADE_NOT_FOUND",
  "QUALITY_GRADE_INACTIVE",
  "QUALITY_GRADE_VERSION_CONFLICT",
  "QUALITY_GRADE_NOT_USED",
  "PRICING_RULE_INVALID",

  // --- supplier -------------------------------------------------------------
  "SUPPLIER_NOT_FOUND",
  "SUPPLIER_INACTIVE",
  "SUPPLIER_VERSION_CONFLICT",
  "SUPPLIER_PAYMENT_AMOUNT_INVALID",
  "SUPPLIER_PAYMENT_NOT_FOUND",
  "SUPPLIER_PAYMENT_ALREADY_REVERSED",
  "SUPPLIER_PAYMENT_REVERSAL_EXCEEDS_REMAINING_AMOUNT",
  "SUPPLIER_PAYMENT_REVERSAL_REASON_REQUIRED",
  "SUPPLIER_ACCOUNT_ADJUSTMENT_REASON_REQUIRED",
  "SUPPLIER_ACCOUNT_ADJUSTMENT_AMOUNT_INVALID",
  "SUPPLIER_ACCOUNT_RECONCILIATION_INTEGRITY_FAILURE",
  "SUPPLIER_ACCOUNT_RECONCILIATION_REBUILD_UNSAFE",

  // --- purchase / receiving / inventory ------------------------------------
  "PURCHASE_NOT_FOUND",
  "PURCHASE_EMPTY",
  "PURCHASE_LINE_INVALID",
  "PURCHASE_VERSION_CONFLICT",
  "PURCHASE_ALREADY_CONFIRMED",
  "PURCHASE_ALREADY_DISCARDED",
  "PURCHASE_ALREADY_VOIDED",
  "PURCHASE_NOT_CONFIRMED",
  "PURCHASE_REPLACEMENT_INVALID",
  "PURCHASE_HAS_ACTIVE_RECEIPTS",
  "PURCHASE_CORRECTION_POLICY_UNAVAILABLE",
  "PURCHASE_VOID_REASON_REQUIRED",
  // --- customer order -------------------------------------------------------
  "CUSTOMER_ORDER_NOT_FOUND",
  "CUSTOMER_ORDER_EMPTY",
  "CUSTOMER_ORDER_LINE_INVALID",
  "CUSTOMER_ORDER_VERSION_CONFLICT",
  "CUSTOMER_ORDER_ALREADY_CONFIRMED",
  "CUSTOMER_ORDER_ALREADY_CANCELLED",
  "CUSTOMER_ORDER_CUSTOMER_REQUIRED",
  "CUSTOMER_ORDER_CUSTOMER_NOT_ALLOWED",
  "CUSTOMER_ORDER_PRODUCT_REQUIRED",
  "CUSTOMER_ORDER_PRICE_REQUIRED",
  "CUSTOMER_ORDER_CURRENCY_MISMATCH",
  "CUSTOMER_ORDER_REPLACEMENT_INVALID",
  "CUSTOMER_ORDER_REPLACEMENT_ALREADY_EXISTS",
  // --- supply commitment ---------------------------------------------------
  "SUPPLY_COMMITMENT_NOT_FOUND",
  "SUPPLY_COMMITMENT_EMPTY",
  "SUPPLY_COMMITMENT_LINE_INVALID",
  "SUPPLY_COMMITMENT_VERSION_CONFLICT",
  "SUPPLY_COMMITMENT_ALREADY_CONFIRMED",
  "SUPPLY_COMMITMENT_ALREADY_CANCELLED",
  "SUPPLY_COMMITMENT_PRODUCT_REQUIRED",
  "SUPPLY_COMMITMENT_CURRENCY_MISMATCH",
  "SUPPLY_COMMITMENT_REPLACEMENT_INVALID",
  "SUPPLY_COMMITMENT_REPLACEMENT_ALREADY_EXISTS",
  "RECEIPT_NOT_FOUND",
  "RECEIPT_ALREADY_REVERSED",
  "RECEIPT_QUANTITY_EXCEEDS_PURCHASE",
  "RECEIPT_UNIT_MISMATCH",
  "RECEIPT_REVERSAL_REASON_REQUIRED",
  "INVENTORY_ADJUSTMENT_REASON_REQUIRED",
  "INVENTORY_RECLASSIFICATION_INVALID",
  "INVENTORY_RECLASSIFICATION_REASON_REQUIRED",
  "INVENTORY_RECONCILIATION_INTEGRITY_FAILURE",
  "DELIVERY_NOT_FOUND",
  "DELIVERY_LINE_INVALID",
  "DELIVERY_VERSION_CONFLICT",
  "DELIVERY_ALREADY_DISPATCHED",
  "DELIVERY_ALREADY_CANCELLED",
  "DELIVERY_ALREADY_DELIVERED",
  "DELIVERY_QUANTITY_EXCEEDS_SALE",
  "DELIVERY_RETURN_EXCEEDS_DISPATCH",
  "DELIVERY_PRODUCT_REQUIRED",
  "DELIVERY_REPLACEMENT_FULFILMENT_BLOCKED",
  "DELIVERY_REASON_REQUIRED",
  "DOCUMENT_NOT_FOUND",
  "DOCUMENT_SOURCE_INVALID",
  "DOCUMENT_SHARE_NOT_FOUND",
  "DOCUMENT_SHARE_REVOKED",
  "DOCUMENT_SHARE_EXPIRED",
  "REPORT_INTEGRITY_FAILURE",

  // --- sale ------------------------------------------------------------------
  "SALE_NOT_FOUND",
  "SALE_EMPTY",
  "SALE_LINE_INVALID",
  /** A draft line may be unresolved while typing; posting never may be. */
  "SALE_PRODUCT_REQUIRED",
  /** The referenced catalogue product is absent from the command workspace. */
  "SALE_PRODUCT_NOT_FOUND",
  /** An inactive catalogue product cannot become new posted goods truth. */
  "SALE_PRODUCT_INACTIVE",
  /** Draft snapshot name/unit no longer agrees with the referenced Product. */
  "SALE_PRODUCT_SNAPSHOT_MISMATCH",
  "SALE_QUALITY_GRADE_REQUIRED",
  "SALE_QUALITY_GRADE_NOT_FOUND",
  "SALE_QUALITY_GRADE_INACTIVE",
  "SALE_QUALITY_GRADE_SNAPSHOT_MISMATCH",
  /** Also covers editing or discarding a sale that has already been posted. */
  "SALE_ALREADY_POSTED",
  "SALE_VERSION_CONFLICT",
  "SALE_CURRENCY_MISMATCH",
  /** An update or delete was attempted against a posted sale (BR-SALE-008). */
  "SALE_IMMUTABLE",
  /** Editing or discarding a draft that was already discarded. */
  "SALE_ALREADY_DISCARDED",
  /** A posted sale must have exactly one ledger entry from its posting command. */
  "SALE_POSTING_ENTRY_MISSING",

  // --- sale correction --------------------------------------------------------
  /** Voiding a draft. A draft is discarded; there is no effect to compensate. */
  "SALE_NOT_POSTED",
  "SALE_ALREADY_VOIDED",
  "SALE_VOID_REASON_REQUIRED",
  /** A goods-returned full void cannot stand while any delivered quantity remains with the customer. */
  "SALE_GOODS_RETURN_INCOMPLETE",
  /** A correction replacement must follow a committed void, never an active sale. */
  "SALE_REPLACEMENT_NOT_VOIDED",
  /** One voided sale has one correction successor at most. */
  "SALE_REPLACEMENT_ALREADY_EXISTS",
  /** The actor who voided the sale owns the continuation of that correction. */
  "SALE_REPLACEMENT_ACTOR_MISMATCH",
  /** A wrong-customer correction must actually move to a different customer. */
  "SALE_REPLACEMENT_CUSTOMER_UNCHANGED",
  "SALE_REPLACEMENT_CURRENCY_MISMATCH",

  // --- payment --------------------------------------------------------------
  "PAYMENT_AMOUNT_INVALID",
  "PAYMENT_NOT_FOUND",
  "PAYMENT_ALREADY_REVERSED",
  "PAYMENT_REVERSAL_EXCEEDS_REMAINING_AMOUNT",
  "PAYMENT_REVERSAL_REASON_REQUIRED",
  "PAYMENT_VERSION_CONFLICT",
  "PAYMENT_CURRENCY_MISMATCH",
  "PAYMENT_ALLOCATION_AMOUNT_INVALID",
  "PAYMENT_ALLOCATION_NOT_FOUND",
  "PAYMENT_ALLOCATION_ALREADY_EXISTS",
  "PAYMENT_ALLOCATION_EXCEEDS_PAYMENT",
  "PAYMENT_ALLOCATION_EXCEEDS_SALE",
  "PAYMENT_ALLOCATION_CURRENCY_MISMATCH",
  "PAYMENT_ALLOCATION_SALE_NOT_POSTED",
  "PAYMENT_ALLOCATION_SALE_VOIDED",
  "PAYMENT_ALLOCATION_POLICY_NOT_MANUAL",
  "PAYMENT_ALLOCATION_REVERSAL_EXCEEDS_REMAINING",
  "PAYMENT_ALLOCATION_REVERSAL_ALREADY_EXISTS",
  "PAYMENT_ALLOCATION_REVERSAL_REASON_REQUIRED",

  // --- debt -----------------------------------------------------------------
  "DEBT_ADJUSTMENT_REASON_REQUIRED",
  "DEBT_ADJUSTMENT_AMOUNT_INVALID",
  "ACCOUNT_ADJUSTMENT_NOT_FOUND",
  "ACCOUNT_ADJUSTMENT_INTEGRITY_ERROR",
  "ACCOUNT_RECONCILIATION_INTEGRITY_FAILURE",
  "ACCOUNT_RECONCILIATION_REBUILD_UNSAFE",

  // --- command plumbing -----------------------------------------------------
  "DUPLICATE_COMMAND",
  "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD",
  "COMMAND_IN_PROGRESS",
  "INVALID_COMMAND_PAYLOAD",
  "TRANSACTION_TIME_IN_FUTURE",

  /**
   * A capability that this phase does not implement (for example sale
   * cancellation). Returned by capability probes so the UI can grey out a
   * control without inventing its own knowledge of the roadmap.
   */
  "CASH_ACCOUNT_NOT_FOUND",
  "CASH_ACCOUNT_INACTIVE",
  "CASH_ACCOUNT_VERSION_CONFLICT",
  "CASH_ACCOUNT_ALREADY_INACTIVE",
  "CASH_ACCOUNT_ALREADY_ACTIVE",
  "CASH_ACCOUNT_CUSTODIAN_INVALID",
  "CASH_ACCOUNT_REQUIRED",
  "CASH_ACCOUNT_CURRENCY_MISMATCH",
  "CASH_ACCOUNT_LINK_MISMATCH",
  "CASH_AMOUNT_INVALID",
  "EXPENSE_NOT_FOUND",
  "EXPENSE_ALREADY_REVERSED",
  "CASH_TRANSFER_INVALID",
  "CASH_TRANSFER_NOT_FOUND",
  "CASH_TRANSFER_ALREADY_REVERSED",
  "CASH_RECONCILIATION_INTEGRITY_FAILURE",
  "CASH_RECONCILIATION_REBUILD_UNSAFE",
  "QUALITY_ISSUE_CODE_NOT_FOUND",
  "QUALITY_ISSUE_CODE_INACTIVE",
  "QUALITY_ISSUE_CODE_VERSION_CONFLICT",
  "QUALITY_ISSUE_CODE_ALREADY_ACTIVE",
  "QUALITY_ISSUE_CODE_ALREADY_INACTIVE",
  "GOODS_ARRIVAL_NOT_FOUND",
  "GOODS_ARRIVAL_ALREADY_REVERSED",
  "GOODS_ARRIVAL_HAS_DOWNSTREAM_FACTS",
  "GOODS_ARRIVAL_LINE_INVALID",
  "GOODS_ARRIVAL_PURCHASE_MISMATCH",
  "WEIGHING_REQUIRED",
  "WEIGHING_NOT_USED",
  "WEIGHING_INVALID",
  "QUALITY_INSPECTION_NOT_FOUND",
  "QUALITY_INSPECTION_ALREADY_REVERSED",
  "QUALITY_INSPECTION_QUANTITY_EXCEEDS_ARRIVAL",
  "QUALITY_INSPECTION_INVALID",
  "QUALITY_INSPECTION_HAS_DOWNSTREAM_FACTS",
  "QUALITY_DISPOSITION_SOURCE_NOT_FOUND",
  "QUALITY_DISPOSITION_SOURCE_REVERSED",
  "QUALITY_DISPOSITION_QUANTITY_EXCEEDS_REMAINING",
  "QUALITY_DISPOSITION_INVALID",
  "QUALITY_DISPOSITION_NOT_FOUND",
  "QUALITY_DISPOSITION_ALREADY_REVERSED",
  "QUALITY_DISPOSITION_HAS_DOWNSTREAM_FACTS",
  "COST_OBSERVATION_CORRECTION_TARGET_REQUIRED",
  "COST_OBSERVATION_CORRECTION_TARGET_NOT_FOUND",
  "COST_OBSERVATION_CORRECTION_LINK_INVALID",
  "COST_OBSERVATION_NOT_FOUND",
  "COST_OBSERVATION_ALREADY_RECORDED",
  "RECONCILIATION_OBSERVATION_CORRECTION_TARGET_REQUIRED",
  "RECONCILIATION_OBSERVATION_CORRECTION_TARGET_NOT_FOUND",
  "RECONCILIATION_OBSERVATION_CORRECTION_LINK_INVALID",
  "RECONCILIATION_OBSERVATION_NOT_FOUND",
  "RECONCILIATION_OBSERVATION_ALREADY_RECORDED",
  "DEBT_OBSERVATION_CORRECTION_TARGET_REQUIRED",
  "DEBT_OBSERVATION_CORRECTION_TARGET_NOT_FOUND",
  "DEBT_OBSERVATION_CORRECTION_LINK_INVALID",
  "DEBT_OBSERVATION_NOT_FOUND",
  "DEBT_OBSERVATION_ALREADY_RECORDED",
  "SUPPLY_COMMITMENT_OBSERVATION_CORRECTION_TARGET_REQUIRED",
  "SUPPLY_COMMITMENT_OBSERVATION_CORRECTION_TARGET_NOT_FOUND",
  "SUPPLY_COMMITMENT_OBSERVATION_CORRECTION_LINK_INVALID",
  "SUPPLY_COMMITMENT_OBSERVATION_NOT_FOUND",
  "SUPPLY_COMMITMENT_OBSERVATION_ALREADY_RECORDED",
  "SUPPLIER_OBSERVATION_CORRECTION_TARGET_REQUIRED",
  "SUPPLIER_OBSERVATION_CORRECTION_TARGET_NOT_FOUND",
  "SUPPLIER_OBSERVATION_CORRECTION_LINK_INVALID",
  "SUPPLIER_OBSERVATION_NOT_FOUND",
  "SUPPLIER_OBSERVATION_ALREADY_RECORDED",
  "DEMAND_OBSERVATION_CORRECTION_TARGET_REQUIRED",
  "DEMAND_OBSERVATION_CORRECTION_TARGET_NOT_FOUND",
  "DEMAND_OBSERVATION_CORRECTION_LINK_INVALID",
  "DEMAND_OBSERVATION_NOT_FOUND",
  "DEMAND_OBSERVATION_ALREADY_RECORDED",
  "WORKSPACE_POLICY_ALREADY_EXISTS",
  "WORKSPACE_POLICY_NOT_FOUND",
  "WORKSPACE_POLICY_NOT_DRAFT",
  "WORKSPACE_POLICY_NOT_APPROVED",
  "WORKSPACE_POLICY_EVIDENCE_REQUIRED",
  "WORKSPACE_POLICY_VERSION_CONFLICT",
  "WORKSPACE_POLICY_EFFECTIVE_RANGE_INVALID",
  "COMMAND_NOT_AVAILABLE",
] as const;

export const domainRejectionCodeSchema = z.enum(DOMAIN_REJECTION_CODES);
export type DomainRejectionCode = z.infer<typeof domainRejectionCodeSchema>;

/**
 * Retryability is a property of the code, not of the call site — otherwise two
 * handlers eventually disagree about whether the same failure is worth retrying.
 * `true` means: the identical command may succeed later without human action.
 */
const RETRYABLE_CODES = new Set<DomainRejectionCode>(["COMMAND_IN_PROGRESS"]);

export function isRetryableCode(code: DomainRejectionCode): boolean {
  return RETRYABLE_CODES.has(code);
}
